# Example hosts inventory for route table collector
# Add your actual network devices here

# Example Cisco device
example_router:
  hostname: 192.168.1.1
  platform: cisco_ios
  groups:
    - cisco
  data:
    vendor: cisco
    location: "Data Center 1"

# Add more devices as needed
# router2:
#   hostname: 192.168.1.2
#   platform: cisco_ios
#   groups:
#     - cisco
